[package]
name = "dirscan"
version = "0.1.0"
authors = ["Tom Forbes <tom@tomforb.es>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ignore = "0.4.11"
structopt = "0.3.11"
num_cpus = "1.12.0"
exitcode = "1.1.2"
indexmap = "1.3.2"

[profile.release]
lto = true
codegen-units = 1
opt-level = 3